language: php

php:
  - 5.5
  - 5.6

script:
  - composer install
  - php vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml --bootstrap tests/bootstrap.php tests/
  - CODECLIMATE_REPO_TOKEN=06975fde56d8cec0082f404431c101b0ef2b80dfa5fc18b3fc818aac7f2401bc ./vendor/bin/test-reporter